# enable color support of ls and also add handy aliases                         
if [ -x /usr/bin/dircolors ]; then                                              
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'                                                  
    #alias dir='dir --color=auto'                                               
    #alias vdir='vdir --color=auto'                                             
                                                                                
    alias grep='grep --color=auto'                                              
    alias fgrep='fgrep --color=auto'                                            
    alias egrep='egrep --color=auto'                                            
fi


# enable programmable completion features (you don't need to enable             
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile            
# sources /etc/bash.bashrc).                                                    
if ! shopt -oq posix; then                                                      
  if [ -f /usr/share/bash-completion/bash_completion ]; then                    
    . /usr/share/bash-completion/bash_completion                                
  elif [ -f /etc/bash_completion ]; then                                        
    . /etc/bash_completion                                                      
  fi                                                                            
fi


# Display working directory on command line
export PS1='\[\e[92;1m\]$(whoami) -> \[\e[0m\]\[\e[34;1m\]${PWD/*\//}\[\e[0m\]$ '


# Load our fancy shell 'macros'
if [[ -f "${HOME}/.bash_profile" ]]; then
    source "${HOME}/.bash_profile"
fi
if [[ -f "${HOME}/.bash_prompt" ]]; then
    source ~/.bash_prompt
fi

shopt -s cdspell
