set nocompatible
syntax on                                                                        
filetype on
filetype plugin indent on
set autoindent
set backspace=indent,eol,start
set ruler
set showcmd
set hlsearch
set textwidth=79                                                                 
set colorcolumn=80
set wrap
set linebreak
set nolist
set formatoptions-=t
set et
set tabstop=4
set shiftwidth=4
set expandtab
set smarttab
set mouse=c

" load the types.vim highlighting file, if it exists
autocmd BufRead,BufNewFile *.[ch] let fname = expand('<afile>:p:h') . '/types.vim'
autocmd BufRead,BufNewFile *.[ch] if filereadable(fname)
autocmd BufRead,BufNewFile *.[ch]   exe 'so ' . fname
autocmd BufRead,BufNewFile *.[ch] endif
